// Lookup action types
export const FETCH_LOOKUP = "FETCH_LOOKUP";
export const FETCH_LOOKUP_SUCCESS = "FETCH_LOOKUP_SUCCESS";
export const FETCH_LOOKUP_ERROR = "FETCH_LOOKUP_ERROR";

export const CREATE_LOOKUP = "CREATE_LOOKUP";
export const CREATE_LOOKUP_SUCCESS = "CREATE_LOOKUP_SUCCESS";
export const CREATE_LOOKUP_ERROR = "CREATE_LOOKUP_ERROR";

export const UPDATE_LOOKUP = "UPDATE_LOOKUP";
export const UPDATE_LOOKUP_SUCCESS = "UPDATE_LOOKUP_SUCCESS";
export const UPDATE_LOOKUP_ERROR = "UPDATE_LOOKUP_ERROR";

export const DELETE_LOOKUP = "DELETE_LOOKUP";
export const DELETE_LOOKUP_SUCCESS = "DELETE_LOOKUP_SUCCESS";
export const DELETE_LOOKUP_ERROR = "DELETE_LOOKUP_ERROR";

